export enum RoutePath {
    Account = '/account',
    AccountConnections = '/account/connections',
    AccountReferrals = '/account/referrals',
    AccountSettings = '/account/settings',
    AdminPanelGiftCodes = '/admin-panel/gift-codes',
    AdminPanelIndexer = '/admin-panel/indexer',
    AdminPanelGeneral = '/admin-panel/general',
    AdminPanelFlipBotGeneral = '/admin-panel/flip-bot/general',
    AdminPanelFlipBotServers = '/admin-panel/flip-bot/servers',
    AdminPanelFlipBotFlipping = '/admin-panel/flip-bot/flipping',
    AdminPanelFlipBotRaiding = '/admin-panel/flip-bot/raiding',
    AdminPanelFlipBotRumble = '/admin-panel/flip-bot/rumble',
    AdminPanelFlipBotShop = '/admin-panel/flip-bot/shop',
    AlertsBot = '/alerts-bot',
    BiddingBots = '/bidding-bots',
    BiddingBotsCreate = '/bidding-bots/create',
    BiddingBotsEdit = '/bidding-bots/edit',
    BiddingBotsWallet = '/bidding-bots/wallet',
    Burners = '/burners',
    BurnersCreate = '/burners/create',
    BurnersEdit = '/burners/edit',
    Explore = '/explore',
    CustomBots = '/custom-bots',
    CustomBotsCreate = '/custom-bots/create',
    CustomBotsEdit = '/custom-bots/edit',
    Dashboard = '/dashboard',
    Extensions = '/extensions',
    ExtensionsCreate = '/extensions/create',
    ExtensionsEdit = '/extensions/edit',
    FlipBot = '/flipbot/dashboard',
    FlipBotModuleFlipping = '/flipbot/flipping',
    FlipBotModuleRaiding = '/flipbot/raiding',
    FlipBotModuleRaidingCreate = '/flipbot/raiding/create',
    FlipBotModuleRaidingView = '/flipbot/raiding/raid',
    FlipBotModuleRumble = '/flipbot/rumble',
    FlipBotModuleShop = '/flipbot/shop',
    FlipBotModuleTokenGating = '/flipbot/token-gating',
    FlipProfile = '/profile',
    Integrations = '/integrations',
    IntegrationsAdd = '/integrations/add',
    IntegrationsEdit = '/integrations/edit',
    ListingTrackers = '/listings-trackers',
    ListingTrackersCreate = '/listings-trackers/create',
    ListingTrackersEdit = '/listings-trackers/edit',
    MessageTemplates = '/templates',
    MessageTemplatesAdd = '/templates/create',
    MessageTemplatesEdit = '/templates/edit',
    RarityBot = '/rarity-bot',
    SaleTrackers = '/sales-trackers',
    SaleTrackersCreate = '/sales-trackers/create',
    SaleTrackersEdit = '/sales-trackers/edit',
    Shop = '/shop',
    ShopIndividual = '/shop/individual',
    ShopOrders = '/shop/orders',
    SnipingBots = '/sniping-bots',
    SnipingBotsMySnipes = '/sniping-bots/my-snipes',
    SnipingBotsCreate = '/sniping-bots/create',
    SnipingBotsEdit = '/sniping-bots/edit',
    Status = '/status',
    SweepContests = '/sweep-contests',
    SweepContestsCreate = '/sweep-contests/create',
    SweepContestsEdit = '/sweep-contests/edit',
    Teams = '/teams',
    TeamsEdit = '/teams/edit',
}

export const ROUTE_NAMES: Record<string, string> = {
    [RoutePath.Account]: 'My Account',
    [RoutePath.AccountConnections]: 'My Account',
    [RoutePath.AccountReferrals]: 'My Account',
    [RoutePath.AccountSettings]: 'My Account',
    [RoutePath.AdminPanelGiftCodes]: 'Admin Panel',
    [RoutePath.AdminPanelIndexer]: 'Admin Panel',
    [RoutePath.AdminPanelGeneral]: 'Admin Panel',
    [RoutePath.AdminPanelFlipBotGeneral]: 'FlipSuite',
    [RoutePath.AdminPanelFlipBotServers]: 'FlipSuite Servers',
    [RoutePath.AdminPanelFlipBotFlipping]: 'FlipSuite CoinFlip Module',
    [RoutePath.AdminPanelFlipBotRaiding]: 'FlipSuite Raiding Module',
    [RoutePath.AdminPanelFlipBotRumble]: 'FlipSuite BattleGround Module',
    [RoutePath.AdminPanelFlipBotShop]: 'FlipSuite Shop Module',
    [RoutePath.AlertsBot]: 'Alerts Bot',
    [RoutePath.BiddingBots]: 'Bidding Bots',
    [RoutePath.BiddingBotsCreate]: 'Bidding Bots',
    [RoutePath.BiddingBotsEdit]: 'Bidding Bots',
    [RoutePath.BiddingBotsWallet]: 'Bidding Bots',
    [RoutePath.Burners]: 'Burners',
    [RoutePath.BurnersCreate]: 'Burners',
    [RoutePath.BurnersEdit]: 'Burners',
    [RoutePath.Explore]: 'Explore',
    [RoutePath.CustomBots]: 'Custom Bots',
    [RoutePath.CustomBotsCreate]: 'Custom Bots',
    [RoutePath.CustomBotsEdit]: 'Custom Bots',
    [RoutePath.Dashboard]: 'Dashboard',
    [RoutePath.Extensions]: 'Extensions',
    [RoutePath.ExtensionsCreate]: 'Extensions',
    [RoutePath.ExtensionsEdit]: 'Extensions',
    [RoutePath.FlipBot]: 'FlipSuite',
    [RoutePath.FlipBotModuleFlipping]: 'CoinFlip',
    [RoutePath.FlipBotModuleRaiding]: 'Raiding',
    [RoutePath.FlipBotModuleRaidingCreate]: 'Raiding',
    [RoutePath.FlipBotModuleRaidingView]: 'Raiding',
    [RoutePath.FlipBotModuleRumble]: 'BattleGround',
    [RoutePath.FlipBotModuleShop]: 'Shop',
    [RoutePath.FlipBotModuleTokenGating]: 'TokenGating',
    [RoutePath.FlipProfile]: 'Your FlipProfile',
    [RoutePath.Integrations]: 'Integrations',
    [RoutePath.IntegrationsAdd]: 'Integrations',
    [RoutePath.IntegrationsEdit]: 'Integrations',
    [RoutePath.ListingTrackers]: 'Listings Trackers',
    [RoutePath.ListingTrackersCreate]: 'Listings Trackers',
    [RoutePath.ListingTrackersEdit]: 'Listings Trackers',
    [RoutePath.MessageTemplates]: 'Templates',
    [RoutePath.MessageTemplatesAdd]: 'Templates',
    [RoutePath.MessageTemplatesEdit]: 'Templates',
    [RoutePath.RarityBot]: 'Rarity Bot',
    [RoutePath.SaleTrackers]: 'Sales Trackers',
    [RoutePath.SaleTrackersCreate]: 'Sales Trackers',
    [RoutePath.SaleTrackersEdit]: 'Sales Trackers',
    [RoutePath.Shop]: 'Shop',
    [RoutePath.ShopIndividual]: 'Shop',
    [RoutePath.ShopOrders]: 'Shop',
    [RoutePath.SnipingBots]: 'Sniping Bots',
    [RoutePath.SnipingBotsMySnipes]: 'Sniping Bots',
    [RoutePath.SnipingBotsCreate]: 'Sniping Bots',
    [RoutePath.SnipingBotsEdit]: 'Sniping Bots',
    [RoutePath.Status]: 'Status',
    [RoutePath.SweepContests]: 'Sweep Contests',
    [RoutePath.SweepContestsCreate]: 'Sweep Contests',
    [RoutePath.SweepContestsEdit]: 'Sweep Contests',
    [RoutePath.Teams]: 'Your Teams',
    [RoutePath.TeamsEdit]: 'Your Teams',
};

export const getRouteName = (path: string) => {
    while (ROUTE_NAMES[path] === undefined) {
        const slashIdx = path.lastIndexOf('/');
        if (slashIdx === -1) {
            break;
        }
        path = path.substring(0, slashIdx);
    }

    return ROUTE_NAMES[path] ?? '';
};
